---
driver:
  name: terraform
  variable_files:
    - terraform.tfvars

provisioner:
  name: terraform

platforms:
  - name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        client_pub_ips:  nomad_client_public_ip
        client_tags:     nomad_client_tags
        server_pub_ips:  nomad_server_public_ip
        server_tags:     nomad_server_tags
        frontend_pub_ip: frontend_server_public_ip

suites:
  - name: default
