---
driver:
  name: terraform
  variable_files:
    - terraform.tfvars

provisioner:
  name: terraform

platforms:
  - name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local

suites:
  - name: default
